# Load necessary models

In [1]:
from pymongo import MongoClient
client = MongoClient("mongodb://localhost:27018/")
db = client["picam"]
collection = db["images"]

In [2]:
import clip
import torch
checkpoint_path = "conclip_vit_l14.pt"
device = "cuda"

# the .pt file downloaded from the links above
device = "cuda"
def load_checkpoint(model, checkpoint_path):
	ckpt = torch.load(checkpoint_path, weights_only=False)
	model = model.float()
	model.load_state_dict(ckpt["model"])
	return model

model, preprocess = clip.load("ViT-L/14", device="cuda")
model = load_checkpoint(model, "conclip_vit_l14.pt")
model.eval()
model = model.to(device)

FileNotFoundError: [Errno 2] No such file or directory: 'conclip_vit_l14.pt'

In [ ]:
def predict(texts, features):
    with torch.no_grad():
        text_inputs = clip.tokenize(texts).to(device)
        text_features = model.encode_text(text_inputs)
        text_features /= text_features.norm(dim=-1, keepdim=True)

        similarity = (text_features @ features.T).cpu().numpy()
        return similarity

# Step 1: Assign movement to images

In [ ]:
FEATURE_DIR = "/mnt/ssd0/embeddings/conclip_vit_l14/cathal_features/"

In [ ]:
moves = {"I am sitting on an airplane": "Airplane",
         "I am in a car": "Car",
         "I am in an airport": "Inside",
         "I am cycling": "Cycling",
         "I am walking outside or on the street": "Walking Outside",
         "I am on public transport": "Public Transport",
         "I am inside a building or a house": "Inside"}

insides = {"I am inside a building or a house": "Inside",
           "I am outside": "Outside",
           "I am in a transport": "Transport"}

In [ ]:
import os
from tqdm.auto import tqdm
import numpy as np

from pymongo import UpdateOne
images = sorted(os.listdir(FEATURE_DIR))
# exclude files that start with any of these prefixes
EXCLUDE_PREFIXES = (
    "2016", "2019",
    "202001", "202002", "202003", "202004", "202005", "202006",
)

images = [img for img in images if not img.startswith(EXCLUDE_PREFIXES)]

text_moves = list(moves.keys())
text_insides = list(insides.keys())
texts = text_moves + text_insides
with torch.no_grad():
    text_inputs = clip.tokenize(texts).to(device)
    text_features = model.encode_text(text_inputs)
    text_features /= text_features.norm(dim=-1, keepdim=True)
nm = len(text_moves)

# process this many images per batch
batch_size = 32
for i in tqdm(range(0, len(images), batch_size)):
    batch_images = images[i:i+batch_size]
    batch_features = []
    for image in batch_images:
        if image.endswith(".npy"):
            features = np.load(os.path.join(FEATURE_DIR, image))
            original_name = image.split(".npy")[0]
            batch_features.append((original_name, features))
    
    if batch_features:
        image_names, image_features = zip(*batch_features)
        image_features = np.stack(image_features)
        image_features = torch.tensor(image_features).to(device)
        image_features /= image_features.norm(dim=-1, keepdim=True)
    else:
        continue
   
    # compute similarity in one matrix multiply on device, then move to CPU once
    similarity = (text_features @ image_features.T).cpu().numpy()

    sim_move = similarity[:nm, :]
    sim_inside = similarity[nm:, :]

    # get best labels for each image (vectorized)
    best_move_idxs = np.argmax(sim_move, axis=0)
    best_inside_idxs = np.argmax(sim_inside, axis=0)

    move_labels_list = [moves[text_moves[i]] for i in best_move_idxs]
    inside_labels_list = [insides[text_insides[i]] for i in best_inside_idxs]

    # build bulk ops
    date = image.split("_")[0]
    date =  f"{date[:4]}-{date[4:6]}-{date[6:8]}"
    ops = [
        UpdateOne({"image_path": f"{date}/{name}", "device": "cathal"}, {"$set": {"movement": move_label, "inside_outside": inside_label}})
        for name, move_label, inside_label in zip(image_names, move_labels_list, inside_labels_list)
    ]

    if ops:
        collection.bulk_write(ops)

  0%|          | 0/40050 [00:00<?, ?it/s]

# Step 2: Clustering

In [ ]:
# Run gps_pipeline.py
!python3 gps_pipeline.py

# Step 3: Semantic

In [ ]:
# Run enrich_stops.py
!python3 enrich_stops.py

# Step 4: Visualise

In [ ]:
from generate_day_view import run as generate_day_view
generate_day_view()

In [20]:
def fetch_images(start_ts: float, end_ts: float) -> list:
    images = list(collection.find(
        {"timestamp": {"$gte": start_ts, "$lt": end_ts}, "device": "cathal"},
        {"image_path": 1, "timestamp": 1, "time": 1, "movement": 1, "inside_outside": 1},
        sort=[("timestamp", 1)],
    ))
    return images

In [34]:
import pandas as pd
df = pd.read_csv("files/nominatim_semantic_stops.csv", sep=";")
df

       track_id  ... info
0             0  ...  NaN
1             1  ...  NaN
2             2  ...  NaN
3             2  ...  Car
4             2  ...  NaN
...         ...  ...  ...
49182     15554  ...  NaN
49183     15555  ...  NaN
49184     15556  ...  NaN
49185     15557  ...  NaN
49186     15558  ...  NaN

[49187 rows x 27 columns]

In [27]:
from tqdm.auto import tqdm
# assigning movement labels to "categories" by the images
for idx, row in tqdm(moves.iterrows(), total=len(moves)):
    start_ts = row["start_ts"] * 1000
    end_ts = row["end_ts"] * 1000
    images = fetch_images(start_ts, end_ts)
    if not images:
        continue
    
    # get the most common movement label among the images
    movement_labels = [img.get("movement") for img in images if img.get("movement")]
    if movement_labels:
        most_common_label = max(set(movement_labels), key=movement_labels.count)
        df.at[idx, "movement"] = most_common_label

  0%|          | 0/22282 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
unknown = df[df["name"] == "Unknown Place"]
unknown

       track_id  ...                                        note
43           27  ...  No nearby places within distance threshold
45           27  ...  No nearby places within distance threshold
47           29  ...  No nearby places within distance threshold
48           30  ...  No nearby places within distance threshold
51           33  ...  No nearby places within distance threshold
...         ...  ...                                         ...
49042     15486  ...  No nearby places within distance threshold
49050     15492  ...                      No nearby places found
49072     15509  ...                      No nearby places found
49074     15509  ...                      No nearby places found
49093     15519  ...  No nearby places within distance threshold

[8192 rows x 20 columns]

# Step 5: Try Nominatim

In [45]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="lifelog-picam")
location = geolocator.reverse("53.39814400752409, -6.2409560382974965", language="en", exactly_one=False, namedetails=True)

In [46]:
for loc in location:
    print(loc.raw)
    print(loc.address)

{'place_id': 252608913, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright', 'osm_type': 'way', 'osm_id': 902121700, 'lat': '53.3984163', 'lon': '-6.2403447', 'class': 'building', 'type': 'house', 'place_rank': 30, 'importance': 8.015945677877496e-05, 'addresstype': 'building', 'name': '', 'display_name': '1, Coolock Lane, Santry, Turnapin DED 1986, Fingal, County Dublin, Leinster, D09 X6X4, Ireland', 'address': {'house_number': '1', 'road': 'Coolock Lane', 'suburb': 'Santry', 'city_district': 'Turnapin DED 1986', 'municipality': 'Fingal', 'county': 'County Dublin', 'ISO3166-2-lvl6': 'IE-D', 'region': 'Leinster', 'ISO3166-2-lvl5': 'IE-L', 'postcode': 'D09 X6X4', 'country': 'Ireland', 'country_code': 'ie'}, 'namedetails': None, 'boundingbox': ['53.3983697', '53.3984882', '-6.2403894', '-6.2403010']}
1, Coolock Lane, Santry, Turnapin DED 1986, Fingal, County Dublin, Leinster, D09 X6X4, Ireland

In [33]:
from timezonefinder import TimezoneFinder
tf = TimezoneFinder()
tf.timezone_at(lng=-8.380955, lat=53.776596)

'Europe/Dublin'